    #include <string>
    #include <iostream>
    #include <fstream>
    #include <iomanip>
    #include <unordered_map>
    #include <queue>

    #include "lalr1_fast.tab.h"
    #define YY_DECL extern "C" int yylex()
    
    extern int pass_no;
    using namespace std;

    void check_for_null(const char* ptr){
        if(ptr == NULL) {
            printf("[TITLE_HEADING]Error in allocating memory by strdup\n");
            exit(-1);
        }
    }

#line 21 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[379] =
    {   0,
        0,    0,    0,    0,   95,   93,   90,   89,   89,   59,
       93,   88,   40,   50,   93,   64,   65,   38,   36,   71,
       37,   72,   39,   84,   84,   62,   70,   47,   60,   46,
       63,   68,   69,   52,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       66,   51,   67,   53,   94,   90,   89,   48,    0,   86,
        0,   88,   61,   57,    0,    0,   41,   42,   43,   85,
        0,   91,   85,    0,    0,   85,    0,   84,    0,    0,
       84,    0,   54,   45,   49,   44,   55,   88,   88,   88,
       88,   88,   88,   88,   88,   88,    1,   88,   88,   88,

       88,   88,   88,   14,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   58,   86,    0,   81,   85,   85,
        0,    0,    0,    0,    0,   91,   85,    0,   84,    0,
       85,    0,    0,   84,    0,   84,   56,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   16,   88,   88,    5,   88,   13,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   21,   31,   88,   88,   88,    0,    0,    0,
        0,   85,    0,    0,   92,   85,    0,    0,   85,   84,

       84,    0,   85,   85,    0,    0,    0,    0,    0,    0,
        0,    0,   84,    0,   88,   88,   88,    7,    2,   88,
        8,   88,   88,   88,   88,   15,   88,   88,   88,   88,
       88,   88,   88,   88,    6,   83,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   73,   88,   82,   24,   88,
       88,    0,    0,    0,    0,    0,    0,   85,    0,   85,
        0,    0,    0,   84,   84,    0,    0,    0,   85,   88,
       88,   18,   22,   28,   88,   88,   88,   88,   30,   10,
       88,   88,   88,   88,   88,   88,   88,   88,    9,   88,
       75,   88,   88,   33,   17,   20,    0,    0,   84,   84,

       84,    0,   84,   84,    0,   84,   84,    0,   85,   85,
        0,   32,   88,   88,   88,   11,   88,   88,   88,   80,
       88,   88,   88,   88,   26,   25,   29,    4,   88,   34,
       87,   84,   84,   84,    0,   84,   84,    0,   84,   12,
       88,    3,   78,   23,   88,   88,   88,   79,   27,   88,
       84,   84,    0,   84,   84,    0,   84,    0,   19,   88,
       88,   88,   88,   84,   84,    0,   84,   88,   88,   77,
       88,   84,   76,   74,   88,   88,   35,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   32,
        7,    7,   34,    7,    7,   35,   34,   34,   34,   36,
        7,   34,    7,   34,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,    7,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    6,    1,    7,    7,
        7,    7,    1,    1,    1,    1,    1,    1,    8,    7,
        7,    7,    8,    9,   10,   11,    4,    1,    3,    1,
        1,   12,    7,    8,    7,    7,    7,    8,    4,    4,
        4,    4,   13,    4,    9,    4,   11,    9,    9,    9,
        4,    4,    4,    4,    4,    4,    3,    1,    3,    1
    } ;

static const flex_int16_t yy_base[392] =
    {   0,
        0,    0,    0,    0,  916,  917,  913,  917,  911,  887,
       65,    0,  886,   63,  872,  917,  917,  884,   59,  917,
       60,   58,   70,   88,  136,  917,  917,   49,  883,   55,
      917,  917,  917,  882,  848,   34,   41,   46,   42,   60,
       74,  850,   51,   81,  858,   83,   69,   58,  854,  852,
      917,   91,  917,  917,  917,  900,  917,  917,  125,  895,
      896,    0,  917,  917,  889,  141,  917,  917,  917,  153,
      134,    0,  171,  203,  130,  917,  191,  917,  881,  210,
      218,  222,  871,  917,  917,  917,  134,  837,  839,  847,
      833,  103,  848,  844,  831,  836,  819,  820,  799,  773,

      748,  744,  733,    0,  733,  106,  722,  698,  707,  714,
      707,  713,  696,  699,  711,  696,  701,  695,  119,  115,
      691,  697,  695,  698,  917,  917,  194,  917,  234,  917,
      249,  253,  244,  274,  280,    0,  269,  304,  277,  284,
      312,    0,  310,    0,  317,  328,  717,  695,  684,  692,
      687,  685,  686,  661,  659,  656,  665,  663,  655,  652,
      639,  649,  648,    0,  153,  629,  613,  610,    0,  604,
      604,  592,  600,  587,  588,  570,  577,  563,  577,  557,
      559,  566,    0,    0,  566,  557,  556,  212,  255,  304,
      352,  356,  296,  338,  917,  361,  370,  365,  394,  376,

      917,  337,  401,  917,  431,  145,  131,  439,  425,  589,
      449,  444,    0,  463,  548,  557,  551,    0,    0,  552,
        0,  540,  547,  525,  527,    0,  517,  522,  514,  503,
      498,  479,  493,  469,    0,    0,  483,  460,  451,  442,
      438,  444,  436,  448,  414,    0,  399,    0,    0,  401,
      395,  358,  362,  451,  188,    0,  485,  487,  492,  496,
      501,  430,  468,  511,  457,  520,  528,  535,  539,  379,
      395,    0,    0,    0,  382,  382,  387,  386,  378,    0,
      376,  368,  372,  377,  375,  359,  372,  355,    0,  361,
        0,  355,  342,  340,    0,    0,  562,  240,    0,  531,

      350,  555,    0,  558,  563,  569,  572,  575,  599,  917,
      607,    0,  300,  292,  280,    0,  276,  263,  275,    0,
      276,  271,  266,  245,    0,    0,    0,    0,  230,    0,
      917,  613,  616,  619,  623,  631,  917,  643,  648,    0,
      238,    0,    0,    0,  207,  187,  188,    0,    0,  173,
      651,  655,  658,  661,  667,  675,  685,  691,    0,  166,
      165,  161,  128,  694,  702,  705,  709,   95,   92,    0,
       60,  720,    0,    0,   68,   54,    0,  917,  762,  775,
      785,  798,  811,  824,  832,  840,  847,  850,  863,  870,
      880

    } ;

static const flex_int16_t yy_def[392] =
    {   0,
      378,    1,  379,  379,  378,  378,  378,  378,  378,  378,
      380,  381,  378,  378,  382,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      378,  378,  378,  378,  378,  378,  378,  378,  380,  378,
      380,  381,  378,  378,  378,  382,  378,  378,  378,  378,
      383,  384,  378,  378,  378,  378,  378,  378,  385,  378,
       25,  378,  378,  378,  378,  378,  378,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  378,  378,  378,  378,  378,  378,
      378,  378,  383,  383,  386,  384,  378,  378,  378,  378,
      378,  387,  388,   81,  378,   81,  378,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  378,  389,  389,
      378,  378,  383,  383,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  390,  387,  388,  208,  378,
      378,  388,  146,  378,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  389,  389,  389,  389,  391,  389,  378,  378,  378,
      378,  390,  390,  208,  264,  212,  378,  378,  378,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  389,  389,  264,  264,

      378,  212,  264,  264,  212,  264,  378,  378,  378,  378,
      378,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      378,  264,  264,  264,  212,  378,  378,  378,  378,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      264,  264,  212,  264,  264,  212,  378,  378,  381,  381,
      381,  381,  381,  264,  264,  212,  264,  381,  381,  381,
      381,  264,  381,  381,  381,  381,  381,    0,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378

    } ;

static const flex_int16_t yy_nxt[988] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   25,   26,   27,   28,   29,   30,   31,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   32,    6,   33,
       34,   12,   35,   36,   37,   38,   39,   40,   12,   12,
       41,   12,   42,   12,   43,   12,   44,   45,   46,   47,
       12,   48,   49,   12,   50,   12,   51,   52,   53,   54,
       60,   64,   67,   83,   84,   68,   70,   70,   70,   70,
       86,   87,   71,   92,   63,   63,   69,   72,   63,   89,
       93,   90,   96,   94,   98,   63,   95,  108,   91,  377,

      121,   97,  100,   61,   73,   99,   74,   74,   74,   74,
      101,  109,  102,  122,  376,  103,   63,   75,  119,   76,
       77,  104,   78,  110,   79,  375,  120,  105,  106,   80,
      126,   75,  114,   76,   77,   76,  134,  134,  111,  374,
       78,  112,  115,  116,   65,  117,  135,  118,  139,  139,
       65,   79,   73,  373,   81,   81,   81,   81,  125,   63,
      147,  152,  153,   61,  166,  167,  211,   76,   77,  180,
       78,  129,  129,  129,  129,  182,  181,   82,  371,  183,
      211,   76,   77,   76,  130,  131,  263,  211,   78,  137,
      137,  137,  137,  298,  132,  188,  189,  190,  130,  131,

      130,  211,   76,  138,  140,  231,  140,  370,  232,  141,
      141,  141,  141,  188,  189,  190,   76,  138,   76,   73,
      369,   74,   74,   74,   74,  368,  378,  363,   74,   74,
       74,   74,  362,  361,   76,   77,  144,  144,  144,  144,
      146,  146,  146,  146,   80,  331,  134,  134,   76,   77,
       76,   80,  129,  129,  129,  129,  135,  253,  254,  145,
      255,  360,  191,   82,  191,  130,  131,  192,  192,  192,
      192,  129,  129,  129,  129,  132,  134,  134,  378,  130,
      131,  130,  194,  194,  359,  350,  135,  196,  196,  196,
      196,  349,  135,  256,  132,  200,  200,  195,  134,  134,

       76,  138,  141,  141,  141,  141,  257,  254,  135,  255,
      197,  201,  348,  347,   76,  138,   76,  198,  202,  198,
      346,  345,  199,  199,  199,  199,  207,  344,  208,  201,
      203,  203,  203,  203,  343,  144,  144,  144,  144,  342,
      134,  134,  256,  204,  210,  211,  213,  213,  213,  213,
      135,  212,  341,  205,  340,  200,  200,  204,  145,  204,
      253,  254,  210,  255,  253,  254,  211,  255,  267,  214,
      192,  192,  192,  192,  258,  258,  258,  258,  202,  196,
      196,  196,  196,  199,  199,  199,  199,  130,  196,  196,
      196,  196,   76,  138,  200,  200,  256,  259,  330,  329,

      256,  130,  197,  130,  328,  327,   76,  138,   76,  326,
      201,  197,  260,  260,  260,  260,  325,  202,  324,  203,
      203,  203,  203,  323,  322,   76,  321,  320,  201,  319,
      318,  317,  204,  316,  315,  261,  314,  313,  312,   76,
      296,   76,  205,  208,  209,  209,  204,  295,  204,  203,
      203,  203,  203,  297,  254,  207,  255,  264,  265,  265,
      378,  294,  268,  293,  268,  211,  212,  269,  269,  269,
      269,  263,  205,  210,  211,  303,  304,  304,  378,  378,
      266,  213,  213,  213,  213,  212,  211,  253,  254,  256,
      255,  210,  292,  291,  290,  211,  378,  289,  305,  288,

      378,  287,  286,  378,  214,  258,  258,  258,  258,  263,
      258,  258,  258,  258,  260,  260,  260,  260,  130,  260,
      260,  260,  260,  256,  378,  285,  284,   76,  259,  299,
      300,  300,  130,  259,  130,  283,  282,  261,  306,  306,
      306,   76,  261,   76,  281,  301,  307,  307,  307,  303,
      304,  304,  302,  269,  269,  269,  269,  309,  309,  309,
      309,  266,  280,  301,  253,  254,  279,  255,  248,  308,
      310,  278,  305,  332,  332,  332,  303,  304,  304,  277,
      311,  304,  304,  304,  310,  276,  310,  333,  334,  334,
      336,  336,  336,  339,  339,  339,  302,  275,  274,  305,

      256,  273,  272,  271,  305,  270,  337,  267,  251,  250,
      335,  249,  248,  338,  247,  246,  308,  309,  309,  309,
      309,  245,  244,  243,  337,  309,  309,  309,  309,  242,
      310,  351,  352,  352,  354,  355,  355,  333,  334,  334,
      311,  334,  334,  334,  310,  241,  310,  240,  311,  336,
      336,  336,  239,  238,  353,  237,  236,  356,  235,  234,
      335,  336,  336,  336,  335,  337,  357,  357,  357,  364,
      365,  365,  338,  351,  352,  352,  352,  352,  352,  364,
      365,  365,  337,  337,  338,  351,  352,  352,  233,  358,
      230,  229,  366,  367,  367,  367,  353,  228,  227,  353,

      337,  226,  366,  357,  357,  357,  225,  224,  353,  357,
      357,  357,  364,  365,  365,  223,  356,  222,  221,  337,
      351,  352,  352,  372,  372,  372,  358,  333,  334,  334,
      220,  219,  358,  218,  217,  366,  216,  337,  351,  352,
      352,  215,   63,  353,  187,  186,  366,  185,  184,  179,
      335,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  353,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   59,  168,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   62,  165,
      164,   62,   62,   62,   62,   62,   62,   62,   65,  163,

       65,   65,  162,   65,   65,   65,   65,   65,   65,   65,
       65,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  136,  161,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  143,  143,  143,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  206,  206,  209,  209,  209,  160,  209,
      209,  209,  209,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  262,  262,  159,  158,
      262,  262,  252,  157,  252,  156,  155,  252,  252,  252,
      154,  252,  151,  150,  149,  148,   63,  142,  128,   59,

      127,   56,  124,  123,  113,  107,   88,   63,   85,   63,
       66,   63,   58,   57,   56,  378,    5,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378
    } ;

static const flex_int16_t yy_chk[988] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       11,   14,   19,   28,   28,   21,   22,   22,   22,   22,
       30,   30,   23,   37,   19,   21,   21,   23,   14,   36,
       37,   36,   38,   37,   39,   23,   37,   43,   36,  376,

       48,   38,   40,   11,   24,   39,   24,   24,   24,   24,
       40,   43,   40,   48,  375,   40,   52,   24,   47,   24,
       24,   41,   24,   44,   24,  371,   47,   41,   41,   24,
       59,   24,   46,   24,   24,   24,   71,   71,   44,  369,
       24,   44,   46,   46,   66,   46,   71,   46,   75,   75,
       66,   24,   25,  368,   25,   25,   25,   25,   52,   87,
       87,   92,   92,   59,  106,  106,  207,   25,   25,  119,
       25,   70,   70,   70,   70,  120,  119,   25,  363,  120,
      206,   25,   25,   25,   70,   70,  206,  207,   25,   73,
       73,   73,   73,  255,   70,  127,  127,  127,   70,   70,

       70,  206,   73,   73,   77,  165,   77,  362,  165,   77,
       77,   77,   77,  188,  188,  188,   73,   73,   73,   74,
      361,   74,   74,   74,   74,  360,  255,  350,   80,   80,
       80,   80,  347,  346,   74,   74,   81,   81,   81,   81,
       82,   82,   82,   82,   74,  298,  133,  133,   74,   74,
       74,   80,  129,  129,  129,  129,  133,  189,  189,   81,
      189,  345,  131,   82,  131,  129,  129,  131,  131,  131,
      131,  132,  132,  132,  132,  129,  134,  134,  298,  129,
      129,  129,  135,  135,  341,  329,  134,  137,  137,  137,
      137,  324,  135,  189,  132,  139,  139,  135,  193,  193,

      137,  137,  140,  140,  140,  140,  190,  190,  193,  190,
      137,  139,  323,  322,  137,  137,  137,  138,  139,  138,
      321,  319,  138,  138,  138,  138,  143,  318,  143,  139,
      141,  141,  141,  141,  317,  145,  145,  145,  145,  315,
      194,  194,  190,  141,  143,  143,  146,  146,  146,  146,
      194,  143,  314,  141,  313,  202,  202,  141,  145,  141,
      252,  252,  143,  252,  253,  253,  143,  253,  301,  146,
      191,  191,  191,  191,  192,  192,  192,  192,  202,  196,
      196,  196,  196,  198,  198,  198,  198,  192,  197,  197,
      197,  197,  196,  196,  200,  200,  252,  192,  294,  293,

      253,  192,  196,  192,  292,  290,  196,  196,  196,  288,
      200,  197,  199,  199,  199,  199,  287,  200,  286,  203,
      203,  203,  203,  285,  284,  199,  283,  282,  200,  281,
      279,  278,  203,  277,  276,  199,  275,  271,  270,  199,
      251,  199,  203,  209,  209,  209,  203,  250,  203,  205,
      205,  205,  205,  254,  254,  208,  254,  208,  208,  208,
      212,  247,  211,  245,  211,  262,  209,  211,  211,  211,
      211,  262,  205,  208,  208,  265,  265,  265,  212,  212,
      208,  214,  214,  214,  214,  212,  262,  257,  257,  254,
      257,  208,  244,  243,  242,  208,  212,  241,  265,  240,

      212,  239,  238,  263,  214,  258,  258,  258,  258,  263,
      259,  259,  259,  259,  260,  260,  260,  260,  258,  261,
      261,  261,  261,  257,  263,  237,  234,  260,  258,  264,
      264,  264,  258,  259,  258,  233,  232,  260,  266,  266,
      266,  260,  261,  260,  231,  264,  267,  267,  267,  300,
      300,  300,  264,  268,  268,  268,  268,  269,  269,  269,
      269,  266,  230,  264,  297,  297,  229,  297,  228,  267,
      269,  227,  300,  302,  302,  302,  304,  304,  304,  225,
      269,  305,  305,  305,  269,  224,  269,  306,  306,  306,
      307,  307,  307,  308,  308,  308,  302,  223,  222,  304,

      297,  220,  217,  216,  305,  215,  307,  210,  187,  186,
      306,  185,  182,  307,  181,  180,  308,  309,  309,  309,
      309,  179,  178,  177,  307,  311,  311,  311,  311,  176,
      309,  332,  332,  332,  333,  333,  333,  334,  334,  334,
      309,  335,  335,  335,  309,  175,  309,  174,  311,  336,
      336,  336,  173,  172,  332,  171,  170,  333,  168,  167,
      334,  338,  338,  338,  335,  336,  339,  339,  339,  351,
      351,  351,  336,  352,  352,  352,  353,  353,  353,  354,
      354,  354,  339,  336,  338,  355,  355,  355,  166,  339,
      163,  162,  351,  356,  356,  356,  352,  161,  160,  353,

      339,  159,  354,  357,  357,  357,  158,  157,  355,  358,
      358,  358,  364,  364,  364,  156,  356,  155,  154,  357,
      365,  365,  365,  366,  366,  366,  357,  367,  367,  367,
      153,  152,  358,  151,  150,  364,  149,  357,  372,  372,
      372,  148,  147,  365,  124,  123,  366,  122,  121,  118,
      367,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  372,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  380,  107,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  381,  105,
      103,  381,  381,  381,  381,  381,  381,  381,  382,  102,

      382,  382,  101,  382,  382,  382,  382,  382,  382,  382,
      382,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  384,  100,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  385,  385,  385,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  387,  387,  388,  388,  388,   99,  388,
      388,  388,  388,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  390,  390,   98,   97,
      390,  390,  391,   96,  391,   95,   94,  391,  391,  391,
       93,  391,   91,   90,   89,   88,   83,   79,   65,   61,

       60,   56,   50,   49,   45,   42,   35,   34,   29,   18,
       15,   13,   10,    9,    7,    5,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[95] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner/lexer.l"

/* %option noyywrap */

/* TYPE_ID             ^/(?!"yield"|"var"|"permits"|"record"|"sealed")({ID}) */
/* COMMENT             {TRADITIONAL_COMMENT}|{EOL_COMMENT} */
#line 838 "lex.yy.c"

#define INITIAL 0
#define REALLYEND 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 101 "scanner/lexer.l"


#line 1059 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 379 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 917 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DO;
                                          }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 108 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            //return CASE;
                                          }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            //return DEFAULT;
                                          }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            //return SWITCH;
                                          }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return INT;
                                          }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 129 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LONG;
                                          }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 134 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BYTE;
                                          }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 139 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CHAR;
                                          }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 144 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return SHORT;
                                          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return FLOAT;
                                          }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 155 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DOUBLE;
                                          }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 160 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BOOLEAN;
                                          }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 166 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return NEW;
                                          }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 171 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return IF;
                                          }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 176 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return ELSE;
                                          }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 181 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return FOR;
                                          }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 186 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return WHILE;
                                          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 191 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BREAK;
                                          }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 196 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CONTINUE;
                                          }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 201 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                          //   return YIELD;
                                          }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 207 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return TRY;
                                          }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 212 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CATCH;
                                          }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 217 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return FINALLY;
                                          }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 223 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return VOID;
                                          }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 228 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return RETURN;
                                          }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 233 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return PUBLIC;
                                          }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return PRIVATE;
                                          }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 243 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CLASS;
                                          }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 248 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return STATIC;
                                          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 254 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return FINAL;
                                          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 259 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return VAR;
                                          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 264 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return ASSERT;
                                          }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 269 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return THROW;
                                          }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 274 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return THROWS;
                                          }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 280 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return SYNCHRONIZED;
                                          }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 286 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return PLUS;
                                      }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 291 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return MINUS;
                                      }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 296 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return ASTERIK;
                                      }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 301 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DIV;
                                      }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 306 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return MODULO;
                                      }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 311 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return INCREMENT;
                                      }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 316 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DECREMENT;
                                      }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 321 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            // return ARROW;
                                      }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 327 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return GEQ;
                                      }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 332 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LEQ;
                                      }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 337 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return GT;
                                      }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 342 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LT;
                                      }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 347 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return NEQ;
                                      }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 352 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DEQ;
                                      }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 358 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BITWISE_AND;
                                      }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 363 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BITWISE_OR;
                                      }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 368 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BITWISE_XOR;
                                      }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 373 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BITWISE_COMPLEMENT;
                                      }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 378 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LEFT_SHIFT;
                                      }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 383 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return RIGHT_SHIFT;
                                      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 388 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return UNSIGNED_RIGHT_SHIFT;} 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 394 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return AND;
                                      }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 399 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return OR;
                                      }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 404 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return NOT;
                                      }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 410 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return ASSIGN;
                                      }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 416 "scanner/lexer.l"
{
                                                                            yylval.str = yytext;
                                                                            check_for_null(yylval.str);
                                                                            return ASSIGNMENT;
                                                                        }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 422 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return COLON;
 
                                      }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 428 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return QM;
                                      }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 434 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LPAREN;
                                      }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 440 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return RPAREN;
                                      }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 446 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LCURLY;
                                      }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 452 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return RCURLY;
                                      }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 458 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return LSQUARE;
                                      }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 464 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return RSQUARE;
                                      }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 470 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return SEMICOLON;
                                      }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 476 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return COMMA;
                                      }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 482 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return DOT;
                                      }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 488 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return THIS;
                                      }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 493 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return INSTANCEOF;
                                      }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 498 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return SUPER;
                                      }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 503 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                          //   return IMPLEMENTS; 
                                      }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 508 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                          //   return INTERFACE; 
                                      }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 513 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                          //   return EXTENDS; 
                                      }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 518 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return PACKAGE; 
                                      }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 523 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return IMPORT; 
                                      }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 529 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CHAR_LITERAL;
                                        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 535 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BOOLEAN_LITERAL;
                                        }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 541 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return NULL_LITERAL;
                                        }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 547 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str); 
                                            return INTEGER_LITERAL;
                                        }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 553 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return FP_LITERAL;
                                        }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 559 "scanner/lexer.l"
{  
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return STRING;
                                        }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 565 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return TEXT_BLOCK;
                                        }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 571 "scanner/lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return IDENTIFIER;
                                        }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 577 "scanner/lexer.l"
{}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 578 "scanner/lexer.l"
{}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 580 "scanner/lexer.l"
{
                                          int c = yyinput();
                                          if(c == EOF){
                                                // cout <<"Putting downn eof\n";
                                                unput(c);
                                          }
                                       }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 588 "scanner/lexer.l"
{/*ignore it*/}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 591 "scanner/lexer.l"
{ 
                              BEGIN(REALLYEND); 
                              return EOF_; 
                        } 
	YY_BREAK
case YY_STATE_EOF(REALLYEND):
#line 596 "scanner/lexer.l"
{ return 0; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 598 "scanner/lexer.l"
{ printf("Illegal character on line %d: %s\n",yylineno, yytext);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 600 "scanner/lexer.l"
ECHO;
	YY_BREAK
#line 1968 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 379 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 379 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 378);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 600 "scanner/lexer.l"



