    #include <string>
    #include <fstream>
    #include <iomanip>
    #include <unordered_map>
    #include <queue>

    #include "../parser/lalr1.tab.h"
    #define YY_DECL extern "C" int yylex()

    using namespace std;

    void check_for_null(const char* ptr){
        if(ptr == NULL) {
            printf("[TITLE_HEADING]Error in allocating memory by strdup\n");
            exit(-1);
        }
    }

#line 19 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[361] =
    {   0,
        0,    0,    0,    0,   85,   83,   81,   80,   80,   51,
       83,   79,   33,   42,   83,   55,   56,   31,   29,   62,
       30,   63,   32,   75,   75,   53,   61,   39,   52,   38,
       54,   59,   60,   44,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       57,   43,   58,   45,   84,   81,   80,   40,    0,   77,
        0,   79,   52,   49,    0,    0,   34,   35,   76,    0,
        0,   76,    0,    0,   76,    0,   75,    0,    0,   75,
        0,   27,   46,   37,   28,   41,   36,   47,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,

       79,   79,   11,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   50,   77,    0,   72,   76,   76,    0,
        0,    0,    0,    0,    0,   82,   82,   76,    0,   75,
        0,   76,    0,    0,   75,    0,   75,   48,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   13,   79,   79,    2,   79,   10,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   24,   79,   79,   79,    0,    0,    0,    0,   76,
        0,    0,   76,    0,    0,   76,   75,   75,    0,   76,

       76,    0,    0,    0,    0,    0,    0,    0,    0,   75,
        0,   79,   79,   79,    4,    5,   79,   79,   79,   12,
       79,   79,   79,   79,   79,   79,   79,   79,    3,   74,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       64,   79,   73,   17,   79,   79,    0,    0,    0,    0,
        0,    0,   76,    0,   76,    0,    0,    0,   75,   75,
        0,    0,    0,   76,   79,   79,   15,   21,   79,   79,
       79,   23,    7,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,    6,   79,   66,   26,   14,    1,
        0,    0,   75,   75,   75,    0,   75,   75,    0,   75,

       75,    0,   76,   76,    0,   25,   79,   79,    8,   79,
       79,   71,   79,   79,   79,   79,   79,   19,   18,   22,
       78,   75,   75,   75,    0,   75,   75,    0,   75,    9,
       79,   69,   79,   79,   79,   70,   20,   75,   75,    0,
       75,   75,    0,   75,    0,   16,   79,   79,   79,   75,
       75,    0,   75,   79,   79,   68,   75,   67,   65,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   32,
        7,    7,   34,    7,    7,   35,   34,   34,   34,   36,
        7,   34,    7,   34,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,    7,   58,   59,   60,   61,   62,   63,   64,
       65,    7,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    6,    1,    7,    7,
        7,    7,    1,    1,    1,    1,    1,    1,    8,    7,
        7,    7,    8,    9,   10,   11,    4,    1,    3,    1,
        1,   12,    7,    8,    7,    7,    7,    8,    4,    4,
        4,    4,   13,    4,    9,    4,   11,    9,    9,    9,
        4,    4,    4,    4,    4,    3,    1,    3,    1
    } ;

static const flex_int16_t yy_base[374] =
    {   0,
        0,    0,    0,    0,  905,  906,  902,  906,  900,  876,
       64,    0,  875,   62,  861,  906,  906,  873,   58,  906,
       57,   55,   67,   87,  135,  875,  906,   64,  871,   52,
      906,  906,  906,  870,  836,   36,   46,  838,   33,   62,
       73,  837,   34,   83,  844,   89,   87,   44,  837,  835,
      906,   56,  906,  906,  906,  882,  906,  906,  104,  874,
      875,    0,  906,  906,  849,  128,  906,  906,  143,  156,
      108,  173,  205,  127,  906,  182,  906,  786,  188,  192,
      220,  906,  774,  906,  906,  906,  906,  145,  732,  734,
      730,  701,  717,  716,  703,  696,  696,  694,  699,  696,

      694,  691,    0,  691,  114,  692,  683,  692,  698,  684,
      685,  684,  139,  684,  669,  681,  661,  128,  652,  654,
      659,  658,  654,  906,  906,  213,  906,  224,  906,  259,
      263,  245,  251,  256,  225,  906,  697,  267,  276,  282,
      299,  306,    0,  287,    0,  311,  336,  669,  647,  633,
      642,  636,  624,  618,  611,  626,  621,  619,  606,  616,
      614,    0,  105,  596,  600,  584,    0,  579,  571,  568,
      558,  562,  553,  547,  553,  547,  544,  555,  542,  543,
      547,    0,  547,  538,  537,  229,  304,  333,  340,  344,
      264,  290,  349,  379,  383,  387,  392,  906,  292,  394,

      906,  427,  331,  130,  435,  411,  562,  443,  443,    0,
      453,  517,  520,  512,    0,    0,  504,  507,  485,    0,
      477,  484,  468,  455,  458,  441,  455,  439,    0,    0,
      451,  442,  448,  439,  426,  418,  421,  406,  400,  392,
        0,  381,    0,    0,  396,  395,  371,  381,  419,  310,
        0,  477,  482,  487,  491,  498,  382,  425,  506,  515,
      523,  526,  530,  534,  378,  394,    0,    0,  373,  370,
      348,    0,    0,  339,  329,  328,  332,  302,  290,  287,
      300,  296,  286,  245,    0,  231,    0,    0,    0,    0,
      483,  340,    0,  541,  246,  550,    0,  553,  558,  565,

      568,  577,  592,  906,  606,    0,  208,  200,    0,  191,
      189,    0,  190,  180,  171,  141,  150,    0,    0,    0,
      906,  597,  610,  616,  622,  625,  906,  630,  634,    0,
      133,    0,  123,  106,  103,    0,    0,  642,  654,  660,
      669,  672,  678,  684,  687,    0,   82,   69,   69,  696,
      702,  711,  714,   55,   50,    0,  720,    0,    0,  906,
      762,  775,  785,  798,  811,  824,  832,  840,  847,  850,
      863,  870,  880
    } ;

static const flex_int16_t yy_def[374] =
    {   0,
      360,    1,  361,  361,  360,  360,  360,  360,  360,  360,
      362,  363,  360,  360,  364,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      360,  360,  360,  360,  360,  360,  360,  360,  362,  360,
      362,  363,  360,  360,  360,  364,  360,  360,  360,  365,
      366,  360,  360,  360,  360,  360,  360,  367,  360,   25,
      360,  360,  360,  360,  360,  360,  360,  360,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  360,  360,  360,  360,  360,  360,  360,
      360,  365,  365,  368,  366,  360,  360,  360,  360,  360,
      360,  360,  369,  370,   80,  360,   80,  360,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  360,  371,  371,  360,  360,
      365,  365,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  372,  369,  370,  205,  360,  360,  370,  147,
      360,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  371,  371,  371,  371,
      373,  371,  360,  360,  360,  360,  372,  372,  205,  259,
      209,  360,  360,  360,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      371,  371,  259,  259,  360,  209,  259,  259,  209,  259,

      360,  360,  360,  360,  360,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      360,  259,  259,  259,  209,  360,  360,  360,  360,  363,
      363,  363,  363,  363,  363,  363,  363,  259,  259,  209,
      259,  259,  209,  360,  360,  363,  363,  363,  363,  259,
      259,  209,  259,  363,  363,  363,  259,  363,  363,    0,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360
    } ;

static const flex_int16_t yy_nxt[976] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   25,   26,   27,   28,   29,   30,   31,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   32,    6,   33,
       34,   12,   35,   36,   37,   38,   39,   40,   12,   12,
       41,   12,   42,   12,   43,   12,   44,   45,   46,   47,
       12,   48,   49,   12,   50,   51,   52,   53,   54,   60,
       64,   67,   68,   69,   69,   69,   69,   87,   88,   70,
      107,   63,   63,   63,   71,   97,  120,   63,   83,   84,
       85,   90,   63,   91,  108,   93,   98,  359,   94,  121,

       92,   95,   61,   72,   99,   73,   73,   73,   73,  125,
      136,  137,  100,  358,  101,  356,   74,  102,   75,   76,
      103,   77,  124,   78,  355,  109,  104,  105,   79,  110,
       74,   65,   75,   76,   75,  114,  118,   65,  115,   77,
      111,  354,   61,  112,  119,  140,  140,  349,  116,  117,
       78,   72,  348,   80,   80,   80,   80,  225,  133,  133,
      226,  128,  128,  128,  128,  208,   75,   76,  134,   77,
       63,  148,  164,  165,  129,  130,   81,  347,  179,  346,
       75,   76,   75,  173,  131,  180,  208,   77,  129,  130,
      129,  138,  138,  138,  138,  141,  337,  141,  174,  290,

      142,  142,  142,  142,   75,  139,   73,   73,   73,   73,
      145,  145,  145,  145,  186,  187,  188,  336,   75,  139,
       75,   72,  335,   73,   73,   73,   73,  136,  137,   79,
      186,  187,  188,  146,  334,  333,   75,   76,  147,  147,
      147,  147,  128,  128,  128,  128,   79,  133,  133,  332,
       75,   76,   75,  133,  133,  129,  130,  134,  192,  192,
      331,   81,  330,  134,  262,  131,  133,  133,  134,  129,
      130,  129,  189,  136,  189,  320,  134,  190,  190,  190,
      190,  128,  128,  128,  128,  193,  193,  193,  193,  195,
      290,  195,  133,  133,  196,  196,  196,  196,   75,  139,

      197,  197,  134,  204,  131,  205,  248,  249,  194,  250,
      197,  197,   75,  139,   75,  292,  198,  142,  142,  142,
      142,  207,  208,  199,  200,  200,  200,  200,  209,  145,
      145,  145,  145,  199,  198,  252,  249,  201,  250,  207,
      319,  290,  251,  208,  318,  321,  317,  202,  360,  316,
      315,  201,  146,  201,  210,  210,  210,  210,  190,  190,
      190,  190,  253,  253,  253,  253,  208,  193,  193,  193,
      193,  251,  258,  248,  249,  129,  250,  211,  360,  314,
       75,  139,  313,  248,  249,  254,  250,  208,  312,  129,
      194,  129,  311,  310,   75,  139,   75,  193,  193,  193,

      193,  196,  196,  196,  196,  255,  255,  255,  255,  251,
      197,  197,  200,  200,  200,  200,  309,  208,   75,  251,
      194,  291,  249,  258,  250,  201,  198,  308,  256,  205,
      206,  206,   75,  199,   75,  202,  307,  306,  208,  201,
      290,  201,  289,  288,  198,  200,  200,  200,  200,  287,
      286,  204,  209,  259,  260,  260,  263,  251,  263,  360,
      360,  264,  264,  264,  264,  285,  258,  284,  202,  207,
      208,  210,  210,  210,  210,  283,  261,  360,  360,  248,
      249,  360,  250,  282,  209,  248,  249,  207,  250,  281,
      280,  208,  279,  278,  211,  360,  277,  276,  275,  360,

      253,  253,  253,  253,  274,  253,  253,  253,  253,  255,
      255,  255,  255,  129,  273,  251,  255,  255,  255,  255,
      272,  251,   75,  254,  293,  294,  294,  129,  254,  129,
      243,  271,  256,  297,  298,  298,   75,  270,   75,  256,
      295,  300,  300,  300,  301,  301,  301,  296,  264,  264,
      264,  264,  303,  303,  303,  303,  299,  269,  295,  297,
      298,  298,  268,  267,  261,  304,  266,  302,  322,  322,
      322,  297,  298,  298,  265,  305,  298,  298,  298,  304,
      262,  304,  299,  323,  324,  324,  326,  326,  326,  246,
      245,  296,  244,  243,  299,  329,  329,  329,  242,  299,

      241,  240,  327,  239,  238,  237,  325,  236,  235,  328,
      303,  303,  303,  303,  234,  338,  339,  339,  302,  233,
      327,  232,  231,  304,  303,  303,  303,  303,  341,  342,
      342,  230,  229,  305,  323,  324,  324,  304,  340,  304,
      324,  324,  324,  326,  326,  326,  228,  305,  326,  326,
      326,  343,  344,  344,  344,  227,  224,  325,  223,  327,
      350,  351,  351,  325,  222,  221,  328,  220,  327,  219,
      218,  328,  338,  339,  339,  345,  217,  327,  339,  339,
      339,  216,  215,  352,  214,  213,  327,  350,  351,  351,
      338,  339,  339,  212,   63,  340,  353,  353,  353,  136,

      185,  340,  344,  344,  344,  344,  344,  344,  184,  183,
      352,  182,  181,  340,  350,  351,  351,  178,  327,  343,
      338,  339,  339,  177,  176,  345,  175,  172,  345,  357,
      357,  357,  323,  324,  324,  171,  327,  352,  338,  339,
      339,  170,  169,  340,  168,  167,  166,  163,  162,  161,
      160,  159,  352,  158,  157,  325,  156,  155,  154,  153,
      152,  340,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   59,  151,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   62,  150,
      149,   62,   62,   62,   62,   62,   62,   62,   65,   63,

       65,   65,  143,   65,   65,   65,   65,   65,   65,   65,
       65,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  144,  144,  144,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  203,  203,  206,  206,  206,  127,  206,
      206,  206,  206,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  257,  257,   59,  126,
      257,  257,  247,   56,  247,  123,  122,  247,  247,  247,
      113,  247,  106,   96,   89,   63,   86,   82,   63,   66,

       63,   58,   57,   56,  360,    5,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360
    } ;

static const flex_int16_t yy_chk[976] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
       14,   19,   21,   22,   22,   22,   22,   30,   30,   23,
       43,   52,   21,   19,   23,   39,   48,   14,   28,   28,
       28,   36,   23,   36,   43,   37,   39,  355,   37,   48,

       36,   37,   11,   24,   40,   24,   24,   24,   24,   59,
       71,   71,   40,  354,   40,  349,   24,   40,   24,   24,
       41,   24,   52,   24,  348,   44,   41,   41,   24,   44,
       24,   66,   24,   24,   24,   46,   47,   66,   46,   24,
       44,  347,   59,   44,   47,   74,   74,  335,   46,   46,
       24,   25,  334,   25,   25,   25,   25,  163,   70,   70,
      163,   69,   69,   69,   69,  204,   25,   25,   70,   25,
       88,   88,  105,  105,   69,   69,   25,  333,  118,  331,
       25,   25,   25,  113,   69,  118,  204,   25,   69,   69,
       69,   72,   72,   72,   72,   76,  317,   76,  113,  316,

       76,   76,   76,   76,   72,   72,   79,   79,   79,   79,
       80,   80,   80,   80,  126,  126,  126,  315,   72,   72,
       72,   73,  314,   73,   73,   73,   73,  135,  135,   79,
      186,  186,  186,   80,  313,  311,   73,   73,   81,   81,
       81,   81,  128,  128,  128,  128,   73,  132,  132,  310,
       73,   73,   73,  133,  133,  128,  128,  132,  134,  134,
      308,   81,  307,  133,  295,  128,  191,  191,  134,  128,
      128,  128,  130,  134,  130,  286,  191,  130,  130,  130,
      130,  131,  131,  131,  131,  138,  138,  138,  138,  139,
      284,  139,  192,  192,  139,  139,  139,  139,  138,  138,

      140,  140,  192,  144,  131,  144,  187,  187,  138,  187,
      199,  199,  138,  138,  138,  250,  140,  141,  141,  141,
      141,  144,  144,  140,  142,  142,  142,  142,  144,  146,
      146,  146,  146,  199,  140,  188,  188,  142,  188,  144,
      283,  282,  187,  144,  281,  292,  280,  142,  250,  279,
      278,  142,  146,  142,  147,  147,  147,  147,  189,  189,
      189,  189,  190,  190,  190,  190,  203,  193,  193,  193,
      193,  188,  203,  247,  247,  190,  247,  147,  292,  277,
      193,  193,  276,  248,  248,  190,  248,  203,  275,  190,
      193,  190,  274,  271,  193,  193,  193,  194,  194,  194,

      194,  195,  195,  195,  195,  196,  196,  196,  196,  247,
      197,  197,  200,  200,  200,  200,  270,  257,  196,  248,
      194,  249,  249,  257,  249,  200,  197,  269,  196,  206,
      206,  206,  196,  197,  196,  200,  266,  265,  257,  200,
      246,  200,  245,  242,  197,  202,  202,  202,  202,  240,
      239,  205,  206,  205,  205,  205,  208,  249,  208,  209,
      258,  208,  208,  208,  208,  238,  258,  237,  202,  205,
      205,  211,  211,  211,  211,  236,  205,  209,  209,  252,
      252,  258,  252,  235,  209,  291,  291,  205,  291,  234,
      233,  205,  232,  231,  211,  209,  228,  227,  226,  209,

      253,  253,  253,  253,  225,  254,  254,  254,  254,  255,
      255,  255,  255,  253,  224,  252,  256,  256,  256,  256,
      223,  291,  255,  253,  259,  259,  259,  253,  254,  253,
      222,  221,  255,  260,  260,  260,  255,  219,  255,  256,
      259,  261,  261,  261,  262,  262,  262,  259,  263,  263,
      263,  263,  264,  264,  264,  264,  260,  218,  259,  294,
      294,  294,  217,  214,  261,  264,  213,  262,  296,  296,
      296,  298,  298,  298,  212,  264,  299,  299,  299,  264,
      207,  264,  294,  300,  300,  300,  301,  301,  301,  185,
      184,  296,  183,  181,  298,  302,  302,  302,  180,  299,

      179,  178,  301,  177,  176,  175,  300,  174,  173,  301,
      303,  303,  303,  303,  172,  322,  322,  322,  302,  171,
      301,  170,  169,  303,  305,  305,  305,  305,  323,  323,
      323,  168,  166,  303,  324,  324,  324,  303,  322,  303,
      325,  325,  325,  326,  326,  326,  165,  305,  328,  328,
      328,  323,  329,  329,  329,  164,  161,  324,  160,  326,
      338,  338,  338,  325,  159,  158,  326,  157,  329,  156,
      155,  328,  339,  339,  339,  329,  154,  326,  340,  340,
      340,  153,  152,  338,  151,  150,  329,  341,  341,  341,
      342,  342,  342,  149,  148,  339,  343,  343,  343,  137,

      123,  340,  344,  344,  344,  345,  345,  345,  122,  121,
      341,  120,  119,  342,  350,  350,  350,  117,  344,  343,
      351,  351,  351,  116,  115,  344,  114,  112,  345,  352,
      352,  352,  353,  353,  353,  111,  344,  350,  357,  357,
      357,  110,  109,  351,  108,  107,  106,  104,  102,  101,
      100,   99,  352,   98,   97,  353,   96,   95,   94,   93,
       92,  357,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  362,   91,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  363,   90,
       89,  363,  363,  363,  363,  363,  363,  363,  364,   83,

      364,  364,   78,  364,  364,  364,  364,  364,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  367,  367,  367,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  369,  369,  370,  370,  370,   65,  370,
      370,  370,  370,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  372,  372,   61,   60,
      372,  372,  373,   56,  373,   50,   49,  373,  373,  373,
       45,  373,   42,   38,   35,   34,   29,   26,   18,   15,

       13,   10,    9,    7,    5,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"


/* TYPE_ID             ^/(?!"yield"|"var"|"permits"|"record"|"sealed")({ID}) */
#line 827 "lex.yy.c"

#define INITIAL 0
#define REALLYEND 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 95 "lexer.l"


#line 1048 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 906 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "lexer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "lexer.l"
{return INT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "lexer.l"
{return LONG;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "lexer.l"
{return BYTE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "lexer.l"
{return CHAR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "lexer.l"
{return SHORT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "lexer.l"
{return FLOAT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "lexer.l"
{return DOUBLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "lexer.l"
{return BOOLEAN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "lexer.l"
{return NEW;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "lexer.l"
{return IF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "lexer.l"
{return ELSE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "lexer.l"
{return FOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 113 "lexer.l"
{return WHILE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "lexer.l"
{return BREAK;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 115 "lexer.l"
{return CONTINUE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "lexer.l"
{return VOID;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "lexer.l"
{return RETURN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 119 "lexer.l"
{return PUBLIC;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "lexer.l"
{return PRIVATE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "lexer.l"
{return CLASS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "lexer.l"
{return STATIC;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "lexer.l"
{return FINAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "lexer.l"
{return VAR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "lexer.l"
{return ASSERT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "lexer.l"
{return THROW;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "lexer.l"
{return DOUBLE_COLON;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "lexer.l"
{return DIAMOND;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "lexer.l"
{return PLUS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "lexer.l"
{return MINUS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "lexer.l"
{return ASTERIK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "lexer.l"
{return DIV;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "lexer.l"
{return MODULO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "lexer.l"
{return INCREMENT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "lexer.l"
{return DECREMENT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "lexer.l"
{return GEQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "lexer.l"
{return LEQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "lexer.l"
{return GT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "lexer.l"
{return LT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "lexer.l"
{return NEQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "lexer.l"
{return DEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 147 "lexer.l"
{return BITWISE_AND;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 148 "lexer.l"
{return BITWISE_OR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 149 "lexer.l"
{return BITWISE_XOR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 150 "lexer.l"
{return BITWISE_COMPLEMENT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 151 "lexer.l"
{return LEFT_SHIFT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 152 "lexer.l"
{return RIGHT_SHIFT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 153 "lexer.l"
{return UNSIGNED_RIGHT_SHIFT;}  
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 155 "lexer.l"
{return AND;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 156 "lexer.l"
{return OR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 157 "lexer.l"
{return NOT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "lexer.l"
{
                                                                            yylval.str = yytext;
                                                                            check_for_null(yylval.str);
                                                                            return ASSIGNMENT;
                                                                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 165 "lexer.l"
{return COLON;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 166 "lexer.l"
{return QM;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 168 "lexer.l"
{return LPAREN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 169 "lexer.l"
{return RPAREN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 170 "lexer.l"
{return LCURLY;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 171 "lexer.l"
{return RCURLY;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 172 "lexer.l"
{return LSQUARE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 173 "lexer.l"
{return RSQUARE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 174 "lexer.l"
{return SEMICOLON;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 175 "lexer.l"
{return COMMA;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 176 "lexer.l"
{return DOT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 178 "lexer.l"
{return THIS;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 179 "lexer.l"
{return INSTANCEOF;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 180 "lexer.l"
{return SUPER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 181 "lexer.l"
{return IMPLEMENTS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 182 "lexer.l"
{ return INTERFACE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 183 "lexer.l"
{ return EXTENDS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 184 "lexer.l"
{ return PACKAGE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return IMPORT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 187 "lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return CHAR_LITERAL;
                                        }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return BOOLEAN_LITERAL;
                                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 199 "lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return NULL_LITERAL;
                                        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 205 "lexer.l"
{   
                                            //yylval.num = stoi(yytext); 
                                            //check_for_null(yylval.num); 
                                            return INTEGER_LITERAL;
                                        }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 211 "lexer.l"
{   
                                            //yylval.float_num = stof(yytext); 
                                            //check_for_null(yylval.float_num); 
                                            return FP_LITERAL;
                                        }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 217 "lexer.l"
{  
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return STRING;
                                        }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 223 "lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return TEXT_BLOCK;
                                        }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 229 "lexer.l"
{   
                                            yylval.str = strdup(yytext); 
                                            check_for_null(yylval.str);
                                            return IDENTIFIER;
                                        }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 235 "lexer.l"
{}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 236 "lexer.l"
{}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 237 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 239 "lexer.l"
{ BEGIN(REALLYEND); return EOF_; } 
	YY_BREAK
case YY_STATE_EOF(REALLYEND):
#line 241 "lexer.l"
{ return 0; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 243 "lexer.l"
{ printf("Illegal character on line %d: %s\n",yylineno, yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 245 "lexer.l"
ECHO;
	YY_BREAK
#line 1582 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 360);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 245 "lexer.l"



